// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/bayesm.HART.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// breg
vec breg(vec const& y, mat const& X, vec const& betabar, mat const& A);
RcppExport SEXP _bayesm_HART_breg(SEXP ySEXP, SEXP XSEXP, SEXP betabarSEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec const& >::type y(ySEXP);
    Rcpp::traits::input_parameter< mat const& >::type X(XSEXP);
    Rcpp::traits::input_parameter< vec const& >::type betabar(betabarSEXP);
    Rcpp::traits::input_parameter< mat const& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(breg(y, X, betabar, A));
    return rcpp_result_gen;
END_RCPP
}
// cov_helpers_test
Rcpp::List cov_helpers_test(arma::vec const& D_vals, arma::mat const& Phi_vals, arma::vec const& v_in, arma::vec const& mu_in, bool diagonal);
RcppExport SEXP _bayesm_HART_cov_helpers_test(SEXP D_valsSEXP, SEXP Phi_valsSEXP, SEXP v_inSEXP, SEXP mu_inSEXP, SEXP diagonalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec const& >::type D_vals(D_valsSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type Phi_vals(Phi_valsSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type v_in(v_inSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type mu_in(mu_inSEXP);
    Rcpp::traits::input_parameter< bool >::type diagonal(diagonalSEXP);
    rcpp_result_gen = Rcpp::wrap(cov_helpers_test(D_vals, Phi_vals, v_in, mu_in, diagonal));
    return rcpp_result_gen;
END_RCPP
}
// cpwbart_mnl
Rcpp::NumericMatrix cpwbart_mnl(std::string const& trees, Rcpp::List const& cutpoints, arma::mat const& X);
RcppExport SEXP _bayesm_HART_cpwbart_mnl(SEXP treesSEXP, SEXP cutpointsSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string const& >::type trees(treesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List const& >::type cutpoints(cutpointsSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(cpwbart_mnl(trees, cutpoints, X));
    return rcpp_result_gen;
END_RCPP
}
// drawMuHeterCov_test
Rcpp::List drawMuHeterCov_test(arma::mat const& oldbetas, arma::vec const& mubar0, arma::mat const& Amu, arma::vec const& D_vals, arma::mat const& Phi_vals, bool diagonal, int n_draws);
RcppExport SEXP _bayesm_HART_drawMuHeterCov_test(SEXP oldbetasSEXP, SEXP mubar0SEXP, SEXP AmuSEXP, SEXP D_valsSEXP, SEXP Phi_valsSEXP, SEXP diagonalSEXP, SEXP n_drawsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat const& >::type oldbetas(oldbetasSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type mubar0(mubar0SEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type Amu(AmuSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type D_vals(D_valsSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type Phi_vals(Phi_valsSEXP);
    Rcpp::traits::input_parameter< bool >::type diagonal(diagonalSEXP);
    Rcpp::traits::input_parameter< int >::type n_draws(n_drawsSEXP);
    rcpp_result_gen = Rcpp::wrap(drawMuHeterCov_test(oldbetas, mubar0, Amu, D_vals, Phi_vals, diagonal, n_draws));
    return rcpp_result_gen;
END_RCPP
}
// llmnl
double llmnl(vec const& beta, vec const& y, mat const& X);
RcppExport SEXP _bayesm_HART_llmnl(SEXP betaSEXP, SEXP ySEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec const& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< vec const& >::type y(ySEXP);
    Rcpp::traits::input_parameter< mat const& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(llmnl(beta, y, X));
    return rcpp_result_gen;
END_RCPP
}
// lndIWishart
double lndIWishart(double nu, mat const& V, mat const& IW);
RcppExport SEXP _bayesm_HART_lndIWishart(SEXP nuSEXP, SEXP VSEXP, SEXP IWSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< mat const& >::type V(VSEXP);
    Rcpp::traits::input_parameter< mat const& >::type IW(IWSEXP);
    rcpp_result_gen = Rcpp::wrap(lndIWishart(nu, V, IW));
    return rcpp_result_gen;
END_RCPP
}
// lndMvn
double lndMvn(vec const& x, vec const& mu, mat const& rooti);
RcppExport SEXP _bayesm_HART_lndMvn(SEXP xSEXP, SEXP muSEXP, SEXP rootiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec const& >::type x(xSEXP);
    Rcpp::traits::input_parameter< vec const& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< mat const& >::type rooti(rootiSEXP);
    rcpp_result_gen = Rcpp::wrap(lndMvn(x, mu, rooti));
    return rcpp_result_gen;
END_RCPP
}
// rdirichlet
vec rdirichlet(vec const& alpha);
RcppExport SEXP _bayesm_HART_rdirichlet(SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec const& >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rdirichlet(alpha));
    return rcpp_result_gen;
END_RCPP
}
// rhierLinearMixture_rcpp_loop
List rhierLinearMixture_rcpp_loop(List const& regdata, mat const& Z, vec const& deltabar, mat const& Ad, mat const& mubar, mat const& Amu, double nu, mat const& V, double nu_e, vec const& ssq, int R, int keep, int nprint, bool drawdelta, mat olddelta, vec const& a, vec oldprob, vec ind, vec tau, bool useBART, List const& bart_params, bool useHeterCov, List const& var_params, List const& phi_params, mat const& Beta_init);
RcppExport SEXP _bayesm_HART_rhierLinearMixture_rcpp_loop(SEXP regdataSEXP, SEXP ZSEXP, SEXP deltabarSEXP, SEXP AdSEXP, SEXP mubarSEXP, SEXP AmuSEXP, SEXP nuSEXP, SEXP VSEXP, SEXP nu_eSEXP, SEXP ssqSEXP, SEXP RSEXP, SEXP keepSEXP, SEXP nprintSEXP, SEXP drawdeltaSEXP, SEXP olddeltaSEXP, SEXP aSEXP, SEXP oldprobSEXP, SEXP indSEXP, SEXP tauSEXP, SEXP useBARTSEXP, SEXP bart_paramsSEXP, SEXP useHeterCovSEXP, SEXP var_paramsSEXP, SEXP phi_paramsSEXP, SEXP Beta_initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List const& >::type regdata(regdataSEXP);
    Rcpp::traits::input_parameter< mat const& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< vec const& >::type deltabar(deltabarSEXP);
    Rcpp::traits::input_parameter< mat const& >::type Ad(AdSEXP);
    Rcpp::traits::input_parameter< mat const& >::type mubar(mubarSEXP);
    Rcpp::traits::input_parameter< mat const& >::type Amu(AmuSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< mat const& >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type nu_e(nu_eSEXP);
    Rcpp::traits::input_parameter< vec const& >::type ssq(ssqSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type keep(keepSEXP);
    Rcpp::traits::input_parameter< int >::type nprint(nprintSEXP);
    Rcpp::traits::input_parameter< bool >::type drawdelta(drawdeltaSEXP);
    Rcpp::traits::input_parameter< mat >::type olddelta(olddeltaSEXP);
    Rcpp::traits::input_parameter< vec const& >::type a(aSEXP);
    Rcpp::traits::input_parameter< vec >::type oldprob(oldprobSEXP);
    Rcpp::traits::input_parameter< vec >::type ind(indSEXP);
    Rcpp::traits::input_parameter< vec >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< bool >::type useBART(useBARTSEXP);
    Rcpp::traits::input_parameter< List const& >::type bart_params(bart_paramsSEXP);
    Rcpp::traits::input_parameter< bool >::type useHeterCov(useHeterCovSEXP);
    Rcpp::traits::input_parameter< List const& >::type var_params(var_paramsSEXP);
    Rcpp::traits::input_parameter< List const& >::type phi_params(phi_paramsSEXP);
    Rcpp::traits::input_parameter< mat const& >::type Beta_init(Beta_initSEXP);
    rcpp_result_gen = Rcpp::wrap(rhierLinearMixture_rcpp_loop(regdata, Z, deltabar, Ad, mubar, Amu, nu, V, nu_e, ssq, R, keep, nprint, drawdelta, olddelta, a, oldprob, ind, tau, useBART, bart_params, useHeterCov, var_params, phi_params, Beta_init));
    return rcpp_result_gen;
END_RCPP
}
// llmnl_con
double llmnl_con(vec const& betastar, vec const& y, mat const& X, vec const& SignRes);
RcppExport SEXP _bayesm_HART_llmnl_con(SEXP betastarSEXP, SEXP ySEXP, SEXP XSEXP, SEXP SignResSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec const& >::type betastar(betastarSEXP);
    Rcpp::traits::input_parameter< vec const& >::type y(ySEXP);
    Rcpp::traits::input_parameter< mat const& >::type X(XSEXP);
    Rcpp::traits::input_parameter< vec const& >::type SignRes(SignResSEXP);
    rcpp_result_gen = Rcpp::wrap(llmnl_con(betastar, y, X, SignRes));
    return rcpp_result_gen;
END_RCPP
}
// rhierMnlRwMixture_rcpp_loop
List rhierMnlRwMixture_rcpp_loop(List const& lgtdata, mat const& Z, vec const& deltabar, mat const& Ad, mat const& mubar, mat const& Amu, double nu, mat const& V, double s, int R, int keep, int nprint, bool drawdelta, mat olddelta, vec const& a, vec oldprob, mat oldbetas, vec ind, vec const& SignRes, bool useBART, List const& bart_params, bool useHeterCov, List const& var_params, List const& phi_params);
RcppExport SEXP _bayesm_HART_rhierMnlRwMixture_rcpp_loop(SEXP lgtdataSEXP, SEXP ZSEXP, SEXP deltabarSEXP, SEXP AdSEXP, SEXP mubarSEXP, SEXP AmuSEXP, SEXP nuSEXP, SEXP VSEXP, SEXP sSEXP, SEXP RSEXP, SEXP keepSEXP, SEXP nprintSEXP, SEXP drawdeltaSEXP, SEXP olddeltaSEXP, SEXP aSEXP, SEXP oldprobSEXP, SEXP oldbetasSEXP, SEXP indSEXP, SEXP SignResSEXP, SEXP useBARTSEXP, SEXP bart_paramsSEXP, SEXP useHeterCovSEXP, SEXP var_paramsSEXP, SEXP phi_paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List const& >::type lgtdata(lgtdataSEXP);
    Rcpp::traits::input_parameter< mat const& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< vec const& >::type deltabar(deltabarSEXP);
    Rcpp::traits::input_parameter< mat const& >::type Ad(AdSEXP);
    Rcpp::traits::input_parameter< mat const& >::type mubar(mubarSEXP);
    Rcpp::traits::input_parameter< mat const& >::type Amu(AmuSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< mat const& >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type keep(keepSEXP);
    Rcpp::traits::input_parameter< int >::type nprint(nprintSEXP);
    Rcpp::traits::input_parameter< bool >::type drawdelta(drawdeltaSEXP);
    Rcpp::traits::input_parameter< mat >::type olddelta(olddeltaSEXP);
    Rcpp::traits::input_parameter< vec const& >::type a(aSEXP);
    Rcpp::traits::input_parameter< vec >::type oldprob(oldprobSEXP);
    Rcpp::traits::input_parameter< mat >::type oldbetas(oldbetasSEXP);
    Rcpp::traits::input_parameter< vec >::type ind(indSEXP);
    Rcpp::traits::input_parameter< vec const& >::type SignRes(SignResSEXP);
    Rcpp::traits::input_parameter< bool >::type useBART(useBARTSEXP);
    Rcpp::traits::input_parameter< List const& >::type bart_params(bart_paramsSEXP);
    Rcpp::traits::input_parameter< bool >::type useHeterCov(useHeterCovSEXP);
    Rcpp::traits::input_parameter< List const& >::type var_params(var_paramsSEXP);
    Rcpp::traits::input_parameter< List const& >::type phi_params(phi_paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(rhierMnlRwMixture_rcpp_loop(lgtdata, Z, deltabar, Ad, mubar, Amu, nu, V, s, R, keep, nprint, drawdelta, olddelta, a, oldprob, oldbetas, ind, SignRes, useBART, bart_params, useHeterCov, var_params, phi_params));
    return rcpp_result_gen;
END_RCPP
}
// rhierNegbinRw_rcpp_loop
List rhierNegbinRw_rcpp_loop(List const& regdata, List const& hessdata, mat const& Z, mat oldbetas, vec const& deltabar, mat const& Ad, mat const& mubar, mat const& Amu, double nu, mat const& V, double a, double b, int R, int keep, double sbeta, double alphacroot, int nprint, bool drawdelta, mat olddelta, vec const& a_mix, vec oldprob, vec ind, double alpha, bool fixalpha, bool useBART, List const& bart_params, bool useHeterCov, List const& var_params, List const& phi_params);
RcppExport SEXP _bayesm_HART_rhierNegbinRw_rcpp_loop(SEXP regdataSEXP, SEXP hessdataSEXP, SEXP ZSEXP, SEXP oldbetasSEXP, SEXP deltabarSEXP, SEXP AdSEXP, SEXP mubarSEXP, SEXP AmuSEXP, SEXP nuSEXP, SEXP VSEXP, SEXP aSEXP, SEXP bSEXP, SEXP RSEXP, SEXP keepSEXP, SEXP sbetaSEXP, SEXP alphacrootSEXP, SEXP nprintSEXP, SEXP drawdeltaSEXP, SEXP olddeltaSEXP, SEXP a_mixSEXP, SEXP oldprobSEXP, SEXP indSEXP, SEXP alphaSEXP, SEXP fixalphaSEXP, SEXP useBARTSEXP, SEXP bart_paramsSEXP, SEXP useHeterCovSEXP, SEXP var_paramsSEXP, SEXP phi_paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List const& >::type regdata(regdataSEXP);
    Rcpp::traits::input_parameter< List const& >::type hessdata(hessdataSEXP);
    Rcpp::traits::input_parameter< mat const& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< mat >::type oldbetas(oldbetasSEXP);
    Rcpp::traits::input_parameter< vec const& >::type deltabar(deltabarSEXP);
    Rcpp::traits::input_parameter< mat const& >::type Ad(AdSEXP);
    Rcpp::traits::input_parameter< mat const& >::type mubar(mubarSEXP);
    Rcpp::traits::input_parameter< mat const& >::type Amu(AmuSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< mat const& >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type keep(keepSEXP);
    Rcpp::traits::input_parameter< double >::type sbeta(sbetaSEXP);
    Rcpp::traits::input_parameter< double >::type alphacroot(alphacrootSEXP);
    Rcpp::traits::input_parameter< int >::type nprint(nprintSEXP);
    Rcpp::traits::input_parameter< bool >::type drawdelta(drawdeltaSEXP);
    Rcpp::traits::input_parameter< mat >::type olddelta(olddeltaSEXP);
    Rcpp::traits::input_parameter< vec const& >::type a_mix(a_mixSEXP);
    Rcpp::traits::input_parameter< vec >::type oldprob(oldprobSEXP);
    Rcpp::traits::input_parameter< vec >::type ind(indSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type fixalpha(fixalphaSEXP);
    Rcpp::traits::input_parameter< bool >::type useBART(useBARTSEXP);
    Rcpp::traits::input_parameter< List const& >::type bart_params(bart_paramsSEXP);
    Rcpp::traits::input_parameter< bool >::type useHeterCov(useHeterCovSEXP);
    Rcpp::traits::input_parameter< List const& >::type var_params(var_paramsSEXP);
    Rcpp::traits::input_parameter< List const& >::type phi_params(phi_paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(rhierNegbinRw_rcpp_loop(regdata, hessdata, Z, oldbetas, deltabar, Ad, mubar, Amu, nu, V, a, b, R, keep, sbeta, alphacroot, nprint, drawdelta, olddelta, a_mix, oldprob, ind, alpha, fixalpha, useBART, bart_params, useHeterCov, var_params, phi_params));
    return rcpp_result_gen;
END_RCPP
}
// rmixGibbs
List rmixGibbs(mat const& y, mat const& Bbar, mat const& A, double nu, mat const& V, vec const& a, vec const& p, vec const& z);
RcppExport SEXP _bayesm_HART_rmixGibbs(SEXP ySEXP, SEXP BbarSEXP, SEXP ASEXP, SEXP nuSEXP, SEXP VSEXP, SEXP aSEXP, SEXP pSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat const& >::type y(ySEXP);
    Rcpp::traits::input_parameter< mat const& >::type Bbar(BbarSEXP);
    Rcpp::traits::input_parameter< mat const& >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< mat const& >::type V(VSEXP);
    Rcpp::traits::input_parameter< vec const& >::type a(aSEXP);
    Rcpp::traits::input_parameter< vec const& >::type p(pSEXP);
    Rcpp::traits::input_parameter< vec const& >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(rmixGibbs(y, Bbar, A, nu, V, a, p, z));
    return rcpp_result_gen;
END_RCPP
}
// rmixture
List rmixture(int n, vec pvec, List comps);
RcppExport SEXP _bayesm_HART_rmixture(SEXP nSEXP, SEXP pvecSEXP, SEXP compsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< vec >::type pvec(pvecSEXP);
    Rcpp::traits::input_parameter< List >::type comps(compsSEXP);
    rcpp_result_gen = Rcpp::wrap(rmixture(n, pvec, comps));
    return rcpp_result_gen;
END_RCPP
}
// rmultireg
List rmultireg(mat const& Y, mat const& X, mat const& Bbar, mat const& A, double nu, mat const& V);
RcppExport SEXP _bayesm_HART_rmultireg(SEXP YSEXP, SEXP XSEXP, SEXP BbarSEXP, SEXP ASEXP, SEXP nuSEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat const& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< mat const& >::type X(XSEXP);
    Rcpp::traits::input_parameter< mat const& >::type Bbar(BbarSEXP);
    Rcpp::traits::input_parameter< mat const& >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< mat const& >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(rmultireg(Y, X, Bbar, A, nu, V));
    return rcpp_result_gen;
END_RCPP
}
// rtrun
NumericVector rtrun(NumericVector const& mu, NumericVector const& sigma, NumericVector const& a, NumericVector const& b);
RcppExport SEXP _bayesm_HART_rtrun(SEXP muSEXP, SEXP sigmaSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector const& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector const& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector const& >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector const& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rtrun(mu, sigma, a, b));
    return rcpp_result_gen;
END_RCPP
}
// rwishart
List rwishart(double nu, mat const& V);
RcppExport SEXP _bayesm_HART_rwishart(SEXP nuSEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< mat const& >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(rwishart(nu, V));
    return rcpp_result_gen;
END_RCPP
}
// sigma_mu_block_gibbs_R
Rcpp::List sigma_mu_block_gibbs_R(arma::mat L, arma::vec mu, arma::mat const& theta, arma::mat const& delta, arma::mat const& Psi, double nu, arma::vec const& mubar0, double Amu_scalar);
RcppExport SEXP _bayesm_HART_sigma_mu_block_gibbs_R(SEXP LSEXP, SEXP muSEXP, SEXP thetaSEXP, SEXP deltaSEXP, SEXP PsiSEXP, SEXP nuSEXP, SEXP mubar0SEXP, SEXP Amu_scalarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type L(LSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type Psi(PsiSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type mubar0(mubar0SEXP);
    Rcpp::traits::input_parameter< double >::type Amu_scalar(Amu_scalarSEXP);
    rcpp_result_gen = Rcpp::wrap(sigma_mu_block_gibbs_R(L, mu, theta, delta, Psi, nu, mubar0, Amu_scalar));
    return rcpp_result_gen;
END_RCPP
}
// varbart_smoke
Rcpp::List varbart_smoke(arma::mat const& Z, arma::vec const& eta_sq, size_t m, double nu, double lambda, double power, double base, int R_iter, int burn, int keep_every);
RcppExport SEXP _bayesm_HART_varbart_smoke(SEXP ZSEXP, SEXP eta_sqSEXP, SEXP mSEXP, SEXP nuSEXP, SEXP lambdaSEXP, SEXP powerSEXP, SEXP baseSEXP, SEXP R_iterSEXP, SEXP burnSEXP, SEXP keep_everySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat const& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type eta_sq(eta_sqSEXP);
    Rcpp::traits::input_parameter< size_t >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type power(powerSEXP);
    Rcpp::traits::input_parameter< double >::type base(baseSEXP);
    Rcpp::traits::input_parameter< int >::type R_iter(R_iterSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< int >::type keep_every(keep_everySEXP);
    rcpp_result_gen = Rcpp::wrap(varbart_smoke(Z, eta_sq, m, nu, lambda, power, base, R_iter, burn, keep_every));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP cpwbart(SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP cpwvarbart(SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_bayesm_HART_breg", (DL_FUNC) &_bayesm_HART_breg, 4},
    {"_bayesm_HART_cov_helpers_test", (DL_FUNC) &_bayesm_HART_cov_helpers_test, 5},
    {"_bayesm_HART_cpwbart_mnl", (DL_FUNC) &_bayesm_HART_cpwbart_mnl, 3},
    {"_bayesm_HART_drawMuHeterCov_test", (DL_FUNC) &_bayesm_HART_drawMuHeterCov_test, 7},
    {"_bayesm_HART_llmnl", (DL_FUNC) &_bayesm_HART_llmnl, 3},
    {"_bayesm_HART_lndIWishart", (DL_FUNC) &_bayesm_HART_lndIWishart, 3},
    {"_bayesm_HART_lndMvn", (DL_FUNC) &_bayesm_HART_lndMvn, 3},
    {"_bayesm_HART_rdirichlet", (DL_FUNC) &_bayesm_HART_rdirichlet, 1},
    {"_bayesm_HART_rhierLinearMixture_rcpp_loop", (DL_FUNC) &_bayesm_HART_rhierLinearMixture_rcpp_loop, 25},
    {"_bayesm_HART_llmnl_con", (DL_FUNC) &_bayesm_HART_llmnl_con, 4},
    {"_bayesm_HART_rhierMnlRwMixture_rcpp_loop", (DL_FUNC) &_bayesm_HART_rhierMnlRwMixture_rcpp_loop, 24},
    {"_bayesm_HART_rhierNegbinRw_rcpp_loop", (DL_FUNC) &_bayesm_HART_rhierNegbinRw_rcpp_loop, 29},
    {"_bayesm_HART_rmixGibbs", (DL_FUNC) &_bayesm_HART_rmixGibbs, 8},
    {"_bayesm_HART_rmixture", (DL_FUNC) &_bayesm_HART_rmixture, 3},
    {"_bayesm_HART_rmultireg", (DL_FUNC) &_bayesm_HART_rmultireg, 6},
    {"_bayesm_HART_rtrun", (DL_FUNC) &_bayesm_HART_rtrun, 4},
    {"_bayesm_HART_rwishart", (DL_FUNC) &_bayesm_HART_rwishart, 2},
    {"_bayesm_HART_sigma_mu_block_gibbs_R", (DL_FUNC) &_bayesm_HART_sigma_mu_block_gibbs_R, 8},
    {"_bayesm_HART_varbart_smoke", (DL_FUNC) &_bayesm_HART_varbart_smoke, 10},
    {"cpwbart",    (DL_FUNC) &cpwbart,    4},
    {"cpwvarbart", (DL_FUNC) &cpwvarbart, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_bayesm_HART(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
