# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

breg <- function(y, X, betabar, A) {
    .Call(`_bayesm_HART_breg`, y, X, betabar, A)
}

cpwbart_mnl <- function(trees, cutpoints, X) {
    .Call(`_bayesm_HART_cpwbart_mnl`, trees, cutpoints, X)
}

llmnl <- function(beta, y, X) {
    .Call(`_bayesm_HART_llmnl`, beta, y, X)
}

lndIWishart <- function(nu, V, IW) {
    .Call(`_bayesm_HART_lndIWishart`, nu, V, IW)
}

lndMvn <- function(x, mu, rooti) {
    .Call(`_bayesm_HART_lndMvn`, x, mu, rooti)
}

rdirichlet <- function(alpha) {
    .Call(`_bayesm_HART_rdirichlet`, alpha)
}

llmnl_con <- function(betastar, y, X, SignRes = as.numeric( c(0))) {
    .Call(`_bayesm_HART_llmnl_con`, betastar, y, X, SignRes)
}

rhierMnlRwMixture_rcpp_loop <- function(lgtdata, Z, deltabar, Ad, mubar, Amu, nu, V, s, R, keep, nprint, drawdelta, olddelta, a, oldprob, oldbetas, ind, SignRes, useBART, bart_params) {
    .Call(`_bayesm_HART_rhierMnlRwMixture_rcpp_loop`, lgtdata, Z, deltabar, Ad, mubar, Amu, nu, V, s, R, keep, nprint, drawdelta, olddelta, a, oldprob, oldbetas, ind, SignRes, useBART, bart_params)
}

rmixGibbs <- function(y, Bbar, A, nu, V, a, p, z) {
    .Call(`_bayesm_HART_rmixGibbs`, y, Bbar, A, nu, V, a, p, z)
}

rmixture <- function(n, pvec, comps) {
    .Call(`_bayesm_HART_rmixture`, n, pvec, comps)
}

rmultireg <- function(Y, X, Bbar, A, nu, V) {
    .Call(`_bayesm_HART_rmultireg`, Y, X, Bbar, A, nu, V)
}

rtrun <- function(mu, sigma, a, b) {
    .Call(`_bayesm_HART_rtrun`, mu, sigma, a, b)
}

rwishart <- function(nu, V) {
    .Call(`_bayesm_HART_rwishart`, nu, V)
}

